name: 'Setup JDK'

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
