name: Apply Spotless

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotlessApply:
    runs-on:  warp-ubuntu-2204-x64-16x-spot
    timeout-minutes: 45
    permissions:
      contents: write # For commiting formatted files

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-java
      - name: Apply spotless formatting
        run: ./gradlew --init-script gradle/init.gradle.kts --no-configuration-cache --continue spotlessApply
      - name: Apply spotless formatting (build-logic)
        run: ./gradlew --project-dir build-logic --init-script ../gradle/init.gradle.kts --no-configuration-cache --continue spotlessApply
      - name: Apply spotless formatting (app-template)
        run: ./gradlew --project-dir feature/app-builder/app-template --init-script ../../../gradle/init.gradle.kts --no-configuration-cache --continue spotlessApply
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🤖 Apply Spotless
