name: Apply Spotless

on:
  # TODO: We're temporarily disabling spotless on pull requests because applying it creates a large
  #       number of changes, and we're waiting for the right time to apply it.
  # pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotlessApply:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write # For commiting formatted files

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-java
      - name: Apply spotless formatting
        run: ./gradlew --init-script gradle/init.gradle.kts --no-configuration-cache --continue spotlessApply
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🤖 Apply Spotless
